name: transparent_pointer
description: Provides TransparentPointer to control hit testing
version: 1.0.0-nullsafety.0
homepage: https://github.com/spkersten/flutter_transparent_pointer

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
