name: transparent_pointer
description: Provides TransparentPointer to control hit testing
version: 1.0.1
homepage: https://github.com/spkersten/flutter_transparent_pointer

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
